print("Earned amount: ")
print("Bubblegum: $202")
print("Toffee: $118")
print("Ice cream: $2250")
print("Milk chocolatE: $1680")
print("Doughnut: $1075")
print("Pancake: $80")
total = 202 + 118 + 2250 + 1680 + 1075 + 80
print("Income: $", total)
print("Staff expenses:")
staffExpenses = int(input())
print("Other expenses:")
otherExpenses = int(input())
netIncome = total - (staffExpenses + otherExpenses)
print("Net income: $", netIncome)
